imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: config.nmm_portal.yml }
    - { resource: services.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    #strict_variables: ~ cf http://symfony.com/doc/2.7/reference/configuration/twig.html
    strict_variables: false
    globals:
        assets_version: %assets_version%
        profiler: @profiler
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - CanalTPSamCoreBundle
        - CanalTPNmmPortalBundle
        - CanalTPSamEcoreUserManagerBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
             file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
             apply_to: "\.less$"
    assets:
        bootstrap_table_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/bootstrap-extensions/table/dist/bootstrap-table.min.js
            output: components/bootstrap-extensions/table/js/bootstrap-table.min.js
        bootstrap_table_locale_fr_FR:
            inputs:
                - %kernel.root_dir%/../vendor/components/bootstrap-extensions/table/dist/locale/bootstrap-table-fr-FR.js
            output: components/bootstrap-extensions/table/js/locale/bootstrap-table-fr-FR.js
        bootstrap_table_css:
            inputs:
                - %kernel.root_dir%/../vendor/components/bootstrap-extensions/table/dist/bootstrap-table.min.css
            output: components/bootstrap-extensions/table/css/bootstrap-table.min.css
        limit_js:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/limit/jquery.limit-1.2.js
            output: components/jquery/limit/jquery.limit-1.2.js
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../web/components/jquery/jquery.js
    less_filter: lessphp
    auto_configure:
        assetic: true
        knp_menu: true
    customize:
        variables_file: %kernel.root_dir%/../vendor/twbs/bootstrap/less/variables.less




# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            auto_mapping: true
            default:
                    connection:    default
                    mappings:
                        CanalTPSamCoreBundle: ~
                        FOSUserBundle: ~
                        CanalTPSamEcoreUserManagerBundle: ~
                        CanalTPNmmPortalBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CanalTP\SamEcoreUserManagerBundle\Entity\User
    group:
        group_class: CanalTP\SamCoreBundle\Entity\Application
        form:
            type: sam_application_registration
    registration:
        form:
            type: create_user
            handler: sam.registration.form.handler.default
    profile:
        form:
            handler: sam.profile.form.handler.default
    service:
        user_manager: sam.user_manager
    from_email:
        address: noreply@canaltp.fr
        sender_name: No Reply
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
